apiVersion: v1
kind: Namespace
metadata:
  name: home-automation
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-pvc
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 10Gi
---
# Home Assistant Core Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true # Allows mDNS & SSDP local IoT device discovery
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          env:
            - name: TZ
              value: "America/Chicago"
          ports:
            - containerPort: 8123
              name: http
          volumeMounts:
            - mountPath: /config
              name: config-storage
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
      volumes:
        - name: config-storage
          persistentVolumeClaim:
            claimName: home-assistant-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
  namespace: home-automation
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: 8123
      name: http
  selector:
    app: home-assistant
