# Rook-compatible values for ceph-csi-drivers Helm chart in Rook v1.20+
operatorConfig:
  namespace: rook-ceph
  driverSpecDefaults:
    imageSet:
      name: rook-csi-operator-image-set-configmap
    nodePlugin:
      priorityClassName: system-node-critical
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
    controllerPlugin:
      priorityClassName: system-cluster-critical
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

drivers:
  rbd:
    enabled: true
    name: rook-ceph.rbd.csi.ceph.com
  cephfs:
    enabled: true
    name: rook-ceph.cephfs.csi.ceph.com
  nfs:
    enabled: false
    name: rook-ceph.nfs.csi.ceph.com
  nvmeof:
    enabled: false
    name: rook-ceph.nvmeof.csi.ceph.com
