[gaming_vms]
bazzite-gaming-vm ansible_host=10.10.20.52

[gaming_vms:vars]
ansible_user=bazzite
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
