[gaming_vms]
windows11-gaming-vm ansible_host=10.10.20.55

[gaming_vms:vars]
ansible_user=Administrator
ansible_password=changeme_win_password # Or inject via --extra-vars or ansible-vault
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm
ansible_port=5985
