apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: s3-aws-backups-prod-use2-001
  namespace: kube-system
spec:
  name: s3-aws-backups-prod-use2-001
  sseConfiguration:
    rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
