apiVersion: v1
kind: Namespace
metadata:
  name: mealie
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data-pvc
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-meals/mealie:v1.12.0
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
            - name: BASE_URL
              value: "https://recipes.bar2sek.com"
          ports:
            - containerPort: 9000
              name: http
          volumeMounts:
            - mountPath: /app/data
              name: mealie-data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mealie-service
  namespace: mealie
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9000
      name: http
  selector:
    app: mealie
