apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: identity
type: Opaque
stringData:
  secret-key: "GENERATE_VIA_OPENSSL_RAND_BASE64_36"
  db-password: "GENERATE_VIA_OPENSSL_RAND_BASE64_24"
